### PR TITLE
Add iceoryx2 repo

### PR DESCRIPTION
**Pull request by elBoberido**
The pull request adds a new repo, iceoryx2, which will be the home for a Rust based iceoryx.

### CODE REVIEW

**Comment by elBoberido** [comment]
@elfenpiff please also have a look at the config

**Review by elfenpiff — APPROVED** [review]
I reviewed the file, it looks good.

**Comment by netomi** [comment]
can we get an approval from a project lead on this repo? Just to clarify that the name is ok and get everyone on board. Self-service has been enabled just recently and its good if everyone in the project is aware whats going on.

**Comment by elBoberido** [comment]
@budrus please give us a thumbs up :)

**Review by budrus — APPROVED** [review]

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
changes are live.

**Comment by elBoberido** [comment]
@netomi thanks. I just noticed that codecov is not yet working. Is this also something which can be done by self-service? I did not found anything related to codecov in the config file

**Comment by netomi** [comment]
codecov integration is done via a GitHub app, only the iceoryx repo was selected so far. I have also selected the iceoryx2 repo. Should work now. Unfortunately this can not be configured via the self-service.

**Comment by elBoberido** [comment]
Thanks very much

**Pull request merged**
